### ISSUE TITLE
Bug in Chrome, elements not clickable 

### ISSUE THREAD

**Issue by LucasTsolakian** [codyhouse/3d-portfolio-template#2] opened 2018-04-27 06:52 UTC
Bug in Chrome Version 65.0.3325.181 (Official Build), elements on Filter 2 are not clickable.

**Comment by Amjadlm** [comment] 2018-05-10 04:08
3d-portfolio-template is not working

**Comment by Amjadlm** [comment] 2018-05-10 04:08
3d-portfolio-template is not working

**Comment by claudia-romano** [comment] 2018-05-10 11:20
Duplicate of https://github.com/CodyHouse/3d-portfolio-template/issues/1

**Closed as completed by claudia-romano** 2018-05-10 11:20 UTC
