### ISSUE TITLE
3d-portfolio-template is not working

### ISSUE THREAD

**Issue by Amjadlm** [codyhouse/3d-portfolio-template#3] opened 2018-05-10 03:52 UTC
Hi
3d-portfolio-template is not working, there are 3 filters and each have 3 projects. when you click on a project link it open 1 project. problem is each time 1 filter out of 3 is not clickable, but if you keep clicking different filters then other one stop working and the filter that was not working start working.

its not working in google chrome and its not scrolling in Firefox.

thanks
 amjad

**Comment by Amjadlm** [comment] 2018-05-10 04:08
3d-portfolio-template is not working

**Comment by Amjadlm** [comment] 2018-05-10 04:08
3d-portfolio-template is not working

**Comment by claudia-romano** [comment] 2018-05-10 11:20
Duplicate of https://github.com/CodyHouse/3d-portfolio-template/issues/1

**Closed as completed by claudia-romano** 2018-05-10 11:20 UTC
