### ISSUE TITLE
Filter Bug

### ISSUE THREAD

**Issue by derekambrosio** [codyhouse/3d-portfolio-template#1] opened 2018-04-18 16:04 UTC
Hi, I was playing with the 3d Portfolio, great work, but I noticed a bug with filtering. It seems that the project items aren't clickable when you click one of the sort filters. You have to click to another filter and then click back in order for the project title to be clickable. 

Thanks for creating this!

**Comment by LucasTsolakian** [comment] 2018-04-26 13:46
Confirmed here on Chrome Version 65.0.3325.181 (Official Build), elements on Filter 2 are not clickable.

**Comment by Amjadlm** [comment] 2018-05-10 04:07
3d-portfolio-template is not working

**Comment by Amjadlm** [comment] 2018-05-10 04:07
3d-portfolio-template is not working

**Comment by claudia-romano** [comment] 2018-05-10 11:19
Hey guys thanks for the heads-up. It looks like there's an issue on chrome where children of an element rotated by 90deg are not clickable. We are looking into this.

**Comment by Amjadlm** [comment] 2018-05-10 11:37
Thank you so much for looking into this issue , actually I have portfolio which is based on this template  and Its having 12 projects so huge work to make new portfolio. I am looking for jobs right now and sending my portfolio and recruiters having problem to view and even one employer said yesterday that she can not view my projects. if you  solve this issue that will be great help. 

kind reagrds
Amjad

**Comment by Amjadlm** [comment] 2018-05-11 21:05
Thank you so much for looking into this issue.

**Comment by Amjadlm** [comment] 2018-05-18 10:38
Thank you so much for looking into this issue.

**Comment by Amjadlm** [comment] 2018-05-18 10:39
Thank you so much for looking into this issue.

**Comment by Amjadlm** [comment] 2018-05-20 09:39
Hi
3d-portfolio-template is not working, there are 3 filters and each have 3 projects. when you click on a project link it open 1 project. problem is each time 1 filter out of 3 is not clickable, but if you keep clicking different filters then other one stop working and the filter that was not working start working.

its not working in google chrome and its not scrolling in Firefox.

thanks
amjad

**Comment by Amjadlm** [comment] 2018-05-25 22:28
Hello Hello ? Any one out there ?

**Comment by sebastiano-guerriero** [comment] 2018-05-26 08:31
Hi Amjad, we understand this component is no longer working in Chrome, and we'll fix it. Unfortunately, we can't promise the fix will be delivered anytime soon since we're working full-time on the CodyHouse framework these days. If you should find a solution on your side, please feel free to contribute here on Github.

**Comment by Amjadlm** [comment] 2018-05-26 11:52
Hi sebastiano, 
Thank you for reply, well I am designer not developer I tried my best, unfortunately unable to fix it,   its bit sad but thanks for looking into this issue.

**Comment by LucasTsolakian** [comment] 2018-10-30 05:59
Looks like it's working fine again in recent Chrome updates, Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by claudia-romano** [comment] 2018-10-30 17:00
Thanks for the info Lucas. Closing this.

**Closed as completed by claudia-romano** 2018-10-30 17:00 UTC
